// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_commandes
void ui_commandes_screen_init(void);
extern lv_obj_t * ui_commandes;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label11;
void ui_event_ON1(lv_event_t * e);
extern lv_obj_t * ui_ON1;
extern lv_obj_t * ui_Label5;
void ui_event_OFF1(lv_event_t * e);
extern lv_obj_t * ui_OFF1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label12;
void ui_event_ON2(lv_event_t * e);
extern lv_obj_t * ui_ON2;
extern lv_obj_t * ui_Label9;
void ui_event_OFF2(lv_event_t * e);
extern lv_obj_t * ui_OFF2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label15;
void ui_event_SliderPWM(lv_event_t * e);
extern lv_obj_t * ui_SliderPWM;
// SCREEN: ui_donnees
void ui_donnees_screen_init(void);
extern lv_obj_t * ui_donnees;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_temperatureTFT;
extern lv_obj_t * ui_pressureTFT;
extern lv_obj_t * ui_gasTFT;
extern lv_obj_t * ui_brightnessTFT;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
// SCREEN: ui_Reglages
void ui_Reglages_screen_init(void);
extern lv_obj_t * ui_Reglages;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label31;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label33;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label23;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Labelgoodmessage;
extern lv_obj_t * ui_Labelerror;
extern lv_obj_t * ui_Label34;
// SCREEN: ui_wifi
void ui_wifi_screen_init(void);
extern lv_obj_t * ui_wifi;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label14;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_wifi1
void ui_wifi1_screen_init(void);
extern lv_obj_t * ui_wifi1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label17;
void ui_event_Keyboard3(lv_event_t * e);
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_Labelgoodmessage2;
extern lv_obj_t * ui_Labelgoodmessage1;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
