// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_firstpage
void ui_firstpage_screen_init(void);
extern lv_obj_t * ui_firstpage;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Confighome;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_commandes
void ui_commandes_screen_init(void);
extern lv_obj_t * ui_commandes;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label11;
void ui_event_ON1(lv_event_t * e);
extern lv_obj_t * ui_ON1;
extern lv_obj_t * ui_Label5;
void ui_event_OFF1(lv_event_t * e);
extern lv_obj_t * ui_OFF1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label12;
void ui_event_ON2(lv_event_t * e);
extern lv_obj_t * ui_ON2;
extern lv_obj_t * ui_Label9;
void ui_event_OFF2(lv_event_t * e);
extern lv_obj_t * ui_OFF2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label15;
void ui_event_SliderPWM(lv_event_t * e);
extern lv_obj_t * ui_SliderPWM;
// SCREEN: ui_donnees
void ui_donnees_screen_init(void);
extern lv_obj_t * ui_donnees;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_temperatureTFT;
extern lv_obj_t * ui_pressureTFT;
extern lv_obj_t * ui_gasTFT;
extern lv_obj_t * ui_brightnessTFT;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_clockTFT;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
// SCREEN: ui_Wifi1
void ui_Wifi1_screen_init(void);
extern lv_obj_t * ui_Wifi1;
extern lv_obj_t * ui_Label14;
void ui_event_SSIDWifi(lv_event_t * e);
extern lv_obj_t * ui_SSIDWifi;
void ui_event_Keyboardwifi1(lv_event_t * e);
extern lv_obj_t * ui_Keyboardwifi1;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Confighome4;
extern lv_obj_t * ui_Label20;
// SCREEN: ui_Wifi2
void ui_Wifi2_screen_init(void);
extern lv_obj_t * ui_Wifi2;
void ui_event_PASSWORDWifi(lv_event_t * e);
extern lv_obj_t * ui_PASSWORDWifi;
void ui_event_Keyboardwifi2(lv_event_t * e);
extern lv_obj_t * ui_Keyboardwifi2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_verifwifi;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Confighome3;
// SCREEN: ui_User1
void ui_User1_screen_init(void);
void ui_event_User1(lv_event_t * e);
extern lv_obj_t * ui_User1;
void ui_event_MAILUser(lv_event_t * e);
extern lv_obj_t * ui_MAILUser;
extern lv_obj_t * ui_Label28;
void ui_event_Keyboarduser1(lv_event_t * e);
extern lv_obj_t * ui_Keyboarduser1;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Confighome2;
extern lv_obj_t * ui_Label17;
// SCREEN: ui_User2
void ui_User2_screen_init(void);
extern lv_obj_t * ui_User2;
void ui_event_PASSWORDUser(lv_event_t * e);
extern lv_obj_t * ui_PASSWORDUser;
extern lv_obj_t * ui_Label29;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Confighome6;
void ui_event_Keyboarduser2(lv_event_t * e);
extern lv_obj_t * ui_Keyboarduser2;
extern lv_obj_t * ui_verifuser;
// SCREEN: ui_Reglages
void ui_Reglages_screen_init(void);
extern lv_obj_t * ui_Reglages;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label31;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label16;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label33;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label23;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Labelgoodmessage;
extern lv_obj_t * ui_Labelerror;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
