// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_commandes_screen_init(void)
{
    ui_commandes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_commandes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_commandes);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 35);
    lv_obj_set_x(ui_Button7, 0);
    lv_obj_set_y(ui_Button7, 122);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "MENU");

    ui_Label11 = lv_label_create(ui_commandes);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -132);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "APPAREIL 1");

    ui_ON1 = lv_btn_create(ui_commandes);
    lv_obj_set_width(ui_ON1, 60);
    lv_obj_set_height(ui_ON1, 39);
    lv_obj_set_x(ui_ON1, -40);
    lv_obj_set_y(ui_ON1, -100);
    lv_obj_set_align(ui_ON1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ON1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ON1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ON1, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ON1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ON1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "ON");

    ui_OFF1 = lv_btn_create(ui_commandes);
    lv_obj_set_width(ui_OFF1, 60);
    lv_obj_set_height(ui_OFF1, 39);
    lv_obj_set_x(ui_OFF1, 40);
    lv_obj_set_y(ui_OFF1, -100);
    lv_obj_set_align(ui_OFF1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OFF1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OFF1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OFF1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OFF1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_OFF1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "OFF");

    ui_Label12 = lv_label_create(ui_commandes);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -62);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "APPAREIL 2");

    ui_ON2 = lv_btn_create(ui_commandes);
    lv_obj_set_width(ui_ON2, 60);
    lv_obj_set_height(ui_ON2, 39);
    lv_obj_set_x(ui_ON2, -40);
    lv_obj_set_y(ui_ON2, -30);
    lv_obj_set_align(ui_ON2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ON2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ON2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ON2, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ON2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ON2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "ON");

    ui_OFF2 = lv_btn_create(ui_commandes);
    lv_obj_set_width(ui_OFF2, 60);
    lv_obj_set_height(ui_OFF2, 39);
    lv_obj_set_x(ui_OFF2, 40);
    lv_obj_set_y(ui_OFF2, -30);
    lv_obj_set_align(ui_OFF2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OFF2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OFF2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OFF2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OFF2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_OFF2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "OFF");

    ui_Label15 = lv_label_create(ui_commandes);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 17);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "VARIATEUR");

    ui_SliderPWM = lv_slider_create(ui_commandes);
    lv_slider_set_value(ui_SliderPWM, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPWM) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderPWM, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPWM, 164);
    lv_obj_set_height(ui_SliderPWM, 28);
    lv_obj_set_x(ui_SliderPWM, 0);
    lv_obj_set_y(ui_SliderPWM, 52);
    lv_obj_set_align(ui_SliderPWM, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderPWM, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPWM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPWM, lv_color_hex(0x2DA041), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPWM, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPWM, lv_color_hex(0x2DA041), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPWM, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ON1, ui_event_ON1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OFF1, ui_event_OFF1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ON2, ui_event_ON2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OFF2, ui_event_OFF2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderPWM, ui_event_SliderPWM, LV_EVENT_ALL, NULL);

}
