// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_donnees_screen_init(void)
{
    ui_donnees = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_donnees, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_donnees);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 35);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 122);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "MENU");

    ui_Label21 = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 45);
    lv_obj_set_y(ui_Label21, -29);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Pa");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -30);
    lv_obj_set_y(ui_Label22, 68);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "GAZ");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 40);
    lv_obj_set_y(ui_Label24, -100);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "°C");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureTFT = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_temperatureTFT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatureTFT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureTFT, -20);
    lv_obj_set_y(ui_temperatureTFT, -100);
    lv_obj_set_align(ui_temperatureTFT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureTFT, "1200");
    lv_obj_set_style_text_color(ui_temperatureTFT, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatureTFT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatureTFT, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressureTFT = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_pressureTFT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pressureTFT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pressureTFT, -25);
    lv_obj_set_y(ui_pressureTFT, -29);
    lv_obj_set_align(ui_pressureTFT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pressureTFT, "2567200");
    lv_obj_set_style_text_font(ui_pressureTFT, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gasTFT = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_gasTFT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gasTFT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gasTFT, 30);
    lv_obj_set_y(ui_gasTFT, 67);
    lv_obj_set_align(ui_gasTFT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gasTFT, "25672");
    lv_obj_set_style_text_color(ui_gasTFT, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gasTFT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gasTFT, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessTFT = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_brightnessTFT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightnessTFT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brightnessTFT, -25);
    lv_obj_set_y(ui_brightnessTFT, 12);
    lv_obj_set_align(ui_brightnessTFT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brightnessTFT, "2567200");
    lv_obj_set_style_text_font(ui_brightnessTFT, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_donnees);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 45);
    lv_obj_set_y(ui_Label26, 11);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Lux");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_donnees);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 203);
    lv_obj_set_height(ui_Container1, 9);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -58);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_donnees);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 203);
    lv_obj_set_height(ui_Container2, 9);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 43);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container2, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}
