// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project
/*
#include "ui.h"

void change_donnees_on(lv_event_t * e)
{
	// Your code here
}

void set_device1_on(lv_event_t * e)
{
	// Your code here
}

void set_device1_off(lv_event_t * e)
{
	// Your code here
}

void set_device2_on(lv_event_t * e)
{
	// Your code here
}

void set_device2_off(lv_event_t * e)
{
	// Your code here
}

void sliderdimmer(lv_event_t * e)
{
	// Your code here
}

void change_donnees_off(lv_event_t * e)
{
	// Your code here
}

void resetfirebase(lv_event_t * e)
{
	// Your code here
}

void rfidnewpass(lv_event_t * e)
{
	// Your code here
}

void return_rfid_pass(lv_event_t * e)
{
	// Your code here
}

void ssid_wifi(lv_event_t * e)
{
	// Your code here
}

void pass_wifi(lv_event_t * e)
{
	// Your code here
}
*/