// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_device1_on(lv_event_t * e);
void set_device1_off(lv_event_t * e);
void set_device2_on(lv_event_t * e);
void set_device2_off(lv_event_t * e);
void sliderdimmer(lv_event_t * e);
void resetfirebase(lv_event_t * e);
void rfidnewpass(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
