// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_User1_screen_init(void)
{
    ui_User1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_User1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MAILUser = lv_textarea_create(ui_User1);
    lv_obj_set_width(ui_MAILUser, 207);
    lv_obj_set_height(ui_MAILUser, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_MAILUser, 0);
    lv_obj_set_y(ui_MAILUser, -7);
    lv_obj_set_align(ui_MAILUser, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_MAILUser, 1000);
    lv_textarea_set_placeholder_text(ui_MAILUser, "Adresse mail");
    lv_textarea_set_one_line(ui_MAILUser, true);



    ui_Label28 = lv_label_create(ui_User1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, -47);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Saisi votre Adresse Mail");

    ui_Keyboarduser1 = lv_keyboard_create(ui_User1);
    lv_obj_set_width(ui_Keyboarduser1, 235);
    lv_obj_set_height(ui_Keyboarduser1, 129);
    lv_obj_set_x(ui_Keyboarduser1, 0);
    lv_obj_set_y(ui_Keyboarduser1, 97);
    lv_obj_set_align(ui_Keyboarduser1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboarduser1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Button9 = lv_btn_create(ui_User1);
    lv_obj_set_width(ui_Button9, 85);
    lv_obj_set_height(ui_Button9, 30);
    lv_obj_set_x(ui_Button9, 0);
    lv_obj_set_y(ui_Button9, 113);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Confighome2 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Confighome2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Confighome2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Confighome2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Confighome2, "RETOUR");
    lv_obj_set_style_text_align(ui_Confighome2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Confighome2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_User1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -122);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "CONNEXION\nADRESSE MAIL");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MAILUser, ui_event_MAILUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboarduser1, ui_event_Keyboarduser1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_User1, ui_event_User1, LV_EVENT_ALL, NULL);

}
