// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_User2_screen_init(void)
{
    ui_User2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_User2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PASSWORDUser = lv_textarea_create(ui_User2);
    lv_obj_set_width(ui_PASSWORDUser, 207);
    lv_obj_set_height(ui_PASSWORDUser, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_PASSWORDUser, 0);
    lv_obj_set_y(ui_PASSWORDUser, -7);
    lv_obj_set_align(ui_PASSWORDUser, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PASSWORDUser, 1000);
    lv_textarea_set_placeholder_text(ui_PASSWORDUser, "Mot de Passe");
    lv_textarea_set_one_line(ui_PASSWORDUser, true);
    lv_textarea_set_password_mode(ui_PASSWORDUser, true);



    ui_Label29 = lv_label_create(ui_User2);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, -47);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Saisir votre mot de passe");

    ui_Button12 = lv_btn_create(ui_User2);
    lv_obj_set_width(ui_Button12, 85);
    lv_obj_set_height(ui_Button12, 30);
    lv_obj_set_x(ui_Button12, 0);
    lv_obj_set_y(ui_Button12, 113);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Confighome6 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Confighome6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Confighome6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Confighome6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Confighome6, "RETOUR");
    lv_obj_set_style_text_align(ui_Confighome6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Confighome6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboarduser2 = lv_keyboard_create(ui_User2);
    lv_obj_set_width(ui_Keyboarduser2, 235);
    lv_obj_set_height(ui_Keyboarduser2, 129);
    lv_obj_set_x(ui_Keyboarduser2, 0);
    lv_obj_set_y(ui_Keyboarduser2, 97);
    lv_obj_set_align(ui_Keyboarduser2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboarduser2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_verifuser = lv_label_create(ui_User2);
    lv_obj_set_width(ui_verifuser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_verifuser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_verifuser, 0);
    lv_obj_set_y(ui_verifuser, -85);
    lv_obj_set_align(ui_verifuser, LV_ALIGN_CENTER);
    lv_label_set_text(ui_verifuser, "...");
    lv_obj_add_flag(ui_verifuser, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_PASSWORDUser, ui_event_PASSWORDUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboarduser2, ui_event_Keyboarduser2, LV_EVENT_ALL, NULL);

}
