// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Wifi2_screen_init(void)
{
    ui_Wifi2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PASSWORDWifi = lv_textarea_create(ui_Wifi2);
    lv_obj_set_width(ui_PASSWORDWifi, 207);
    lv_obj_set_height(ui_PASSWORDWifi, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_PASSWORDWifi, 0);
    lv_obj_set_y(ui_PASSWORDWifi, -7);
    lv_obj_set_align(ui_PASSWORDWifi, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PASSWORDWifi, 1000);
    lv_textarea_set_placeholder_text(ui_PASSWORDWifi, "Mot de Passe Wifi ...");
    lv_textarea_set_one_line(ui_PASSWORDWifi, true);
    lv_textarea_set_password_mode(ui_PASSWORDWifi, true);



    ui_Keyboardwifi2 = lv_keyboard_create(ui_Wifi2);
    lv_obj_set_width(ui_Keyboardwifi2, 235);
    lv_obj_set_height(ui_Keyboardwifi2, 129);
    lv_obj_set_x(ui_Keyboardwifi2, 0);
    lv_obj_set_y(ui_Keyboardwifi2, 97);
    lv_obj_set_align(ui_Keyboardwifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboardwifi2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label19 = lv_label_create(ui_Wifi2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -47);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Saisir le mot de passe");

    ui_verifwifi = lv_label_create(ui_Wifi2);
    lv_obj_set_width(ui_verifwifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_verifwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_verifwifi, 0);
    lv_obj_set_y(ui_verifwifi, -85);
    lv_obj_set_align(ui_verifwifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_verifwifi, "...");
    lv_obj_add_flag(ui_verifwifi, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Button11 = lv_btn_create(ui_Wifi2);
    lv_obj_set_width(ui_Button11, 85);
    lv_obj_set_height(ui_Button11, 30);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, 113);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Confighome3 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Confighome3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Confighome3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Confighome3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Confighome3, "RETOUR");
    lv_obj_set_style_text_align(ui_Confighome3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Confighome3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PASSWORDWifi, ui_event_PASSWORDWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboardwifi2, ui_event_Keyboardwifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
