// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_wifi1_screen_init(void)
{
    ui_wifi1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea2 = lv_textarea_create(ui_wifi1);
    lv_obj_set_width(ui_TextArea2, 194);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, -30);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "MOT DE PASSE WIFI");
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_textarea_set_password_mode(ui_TextArea2, true);



    ui_Button11 = lv_btn_create(ui_wifi1);
    lv_obj_set_width(ui_Button11, 106);
    lv_obj_set_height(ui_Button11, 35);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, 40);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "CONNEXION");

    ui_Keyboard3 = lv_keyboard_create(ui_wifi1);
    lv_obj_set_width(ui_Keyboard3, 237);
    lv_obj_set_height(ui_Keyboard3, 120);
    lv_obj_set_x(ui_Keyboard3, 0);
    lv_obj_set_y(ui_Keyboard3, 97);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Labelgoodmessage2 = lv_label_create(ui_wifi1);
    lv_obj_set_width(ui_Labelgoodmessage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelgoodmessage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelgoodmessage2, 0);
    lv_obj_set_y(ui_Labelgoodmessage2, -82);
    lv_obj_set_align(ui_Labelgoodmessage2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelgoodmessage2, "WIFI CONNECTE");
    lv_obj_add_flag(ui_Labelgoodmessage2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Labelgoodmessage2, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelgoodmessage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelgoodmessage2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelgoodmessage1 = lv_label_create(ui_wifi1);
    lv_obj_set_width(ui_Labelgoodmessage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelgoodmessage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelgoodmessage1, 0);
    lv_obj_set_y(ui_Labelgoodmessage1, -82);
    lv_obj_set_align(ui_Labelgoodmessage1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelgoodmessage1, "ERREUR");
    lv_obj_add_flag(ui_Labelgoodmessage1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Labelgoodmessage1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelgoodmessage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelgoodmessage1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_wifi1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -93);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Saissisez le mot de passe");
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard3, ui_event_Keyboard3, LV_EVENT_ALL, NULL);

}
