// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Wifi1_screen_init(void)
{
    ui_Wifi1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Wifi1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -47);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Saisir le SSID de votre Wifi");

    ui_SSIDWifi = lv_textarea_create(ui_Wifi1);
    lv_obj_set_width(ui_SSIDWifi, 207);
    lv_obj_set_height(ui_SSIDWifi, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_SSIDWifi, 0);
    lv_obj_set_y(ui_SSIDWifi, -7);
    lv_obj_set_align(ui_SSIDWifi, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_SSIDWifi, 1000);
    lv_textarea_set_placeholder_text(ui_SSIDWifi, "SSID Wifi ...");
    lv_textarea_set_one_line(ui_SSIDWifi, true);



    ui_Keyboardwifi1 = lv_keyboard_create(ui_Wifi1);
    lv_obj_set_width(ui_Keyboardwifi1, 235);
    lv_obj_set_height(ui_Keyboardwifi1, 129);
    lv_obj_set_x(ui_Keyboardwifi1, 0);
    lv_obj_set_y(ui_Keyboardwifi1, 97);
    lv_obj_set_align(ui_Keyboardwifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboardwifi1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Button14 = lv_btn_create(ui_Wifi1);
    lv_obj_set_width(ui_Button14, 85);
    lv_obj_set_height(ui_Button14, 30);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, 113);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Confighome4 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Confighome4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Confighome4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Confighome4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Confighome4, "RETOUR");
    lv_obj_set_style_text_align(ui_Confighome4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Confighome4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Wifi1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, -122);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "CONNEXION\nWIFI");
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SSIDWifi, ui_event_SSIDWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboardwifi1, ui_event_Keyboardwifi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);

}
